export type ProviderSignupFormdataType = {
  type: string;
  category: string;
  RegName?: string;
  companyName?: string;
  name: string;
  email: string;
  password: string;
  confirmpassword: string;
  number: number;
  DOB: Date;
  address1: string;
  address2: string;
  city: string;
  state: string;
  description: string;
  certificate: File | null;
  CompanyCertificate: File | null;
  regNumber: string;
  profilePic: File | null;
  companyLogo: File | null;
  otp?: string;
  isSubProfile?: boolean;
  masterID?: string;
  companyName?: string;
  aadhar?: File | null;
  PAN?: File | null;
  agreed?: boolean;
  gst?: string;
};
